# Generated by Django 4.2.7 on 2023-11-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MchoiceTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naloge.task')),
            ],
            bases=('naloge.task',),
        ),
        migrations.CreateModel(
            name='MchoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpr', models.CharField(max_length=200, verbose_name='vprašanje')),
                ('nal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naloge.mchoicetask', verbose_name='Naloga vprašanja')),
            ],
        ),
        migrations.CreateModel(
            name='MchoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=200, verbose_name='odgovor')),
                ('odg', models.CharField(blank=True, max_length=200, verbose_name='odgovor, ki ga dobi uporabnik, če izbere ta odgovor')),
                ('prav', models.BooleanField(default=False, verbose_name='odgovor je pravilen')),
                ('vpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naloge.mchoicequestion', verbose_name='vprašanje')),
            ],
        ),
    ]
