# Generated by Django 4.2.7 on 2023-11-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0003_alter_mchoicequestion_vpr_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='display_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mchoiceanswer',
            name='vpr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='naloge.mchoicequestion', verbose_name='vprašanje'),
        ),
        migrations.AlterField(
            model_name='mchoicequestion',
            name='nal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='naloge.mchoicetask', verbose_name='Naloga vprašanja'),
        ),
    ]
