# Generated by Django 4.2.7 on 2023-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0004_task_display_name_alter_mchoiceanswer_vpr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mchoiceanswer',
            name='odg',
        ),
        migrations.AddField(
            model_name='mchoicequestion',
            name='kom',
            field=models.CharField(blank=True, max_length=200, verbose_name='komentar po rešenem vprašanju'),
        ),
    ]
