# Generated by Django 4.2.7 on 2023-11-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0005_remove_mchoiceanswer_odg_mchoicequestion_kom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchoicequestion',
            name='kom',
            field=models.CharField(blank=True, max_length=500, verbose_name='komentar po rešenem vprašanju'),
        ),
    ]
